# Assignment Instruction

This is part 2 of assignment 1. It amounts to 60 percent of the grade.

In this part of the assignment, you will explore covid-19 data from the US. 

The dataset is:

1. At the county level
2. Including deaths and case figures
3. On 1 Oct 2020.

"This dataset contains daily updated number of reported cases & deaths in the US on the state and county level, as provided by the Johns Hopkins University." It is downloaded from https://www.kaggle.com/headsortails/covid19-us-county-jhu-data-demographics

In addition, you will use two additional datasets regarding the demography of the counties and political factors.

1. County demography
    - https://www.kaggle.com/muonneutrino/us-census-demographic-data
2. The county-level outcomes of the 2016 US Presidential Election
    - https://www.kaggle.com/stevepalley/2016uspresidentialvotebycounty

The data files are found in `Data` directory of this repository. You can download the files, and upload.

# Import packages

In [1]:
import numpy as np
import pandas as pd

# Covid data (15 percent)

## Read data

Open `covid_us_county_oct20.csv`, and print the first 10 rows

In [2]:
covid_file = pd.read_csv(r"C:\Users\jacob\Downloads\covid_us_county_oct20.csv")
covid_file.head(10)

,fips,county,state,lat,long,date,cases,state_code,deaths
0,1001,Autauga,Alabama,32.539527,-86.644082,2020-10-01,1798,AL,28
1,1003,Baldwin,Alabama,30.727750,-87.722071,2020-10-01,5997,AL,53
2,1005,Barbour,Alabama,31.868263,-85.387129,2020-10-01,898,AL,7
3,1007,Bibb,Alabama,32.996421,-87.125115,2020-10-01,672,AL,10
4,1009,Blount,Alabama,33.982109,-86.567906,2020-10-01,1634,AL,15
5,1011,Bullock,Alabama,32.100305,-85.712655,2020-10-01,612,AL,16
6,1013,Butler,Alabama,31.753001,-86.680575,2020-10-01,919,AL,40
7,1015,Calhoun,Alabama,33.774837,-85.826304,2020-10-01,3587,AL,44
8,1017,Chambers,Alabama,32.913601,-85.390727,2020-10-01,1181,AL,42
9,1019,Cherokee,Alabama,34.178060,-85.606390,2020-10-01,624,AL,13

## Answer the following questions

1. How many rows in the dataset?
2. What's the highest count of cases? In which county?
3. Count the number of counties in each US State
4. Calculate the following numbers by US States
    - Cases
    - Deaths

In [3]:
#number of rows in the dataset 
covid_file.shape
#915,160 rows in the dataset

(3241, 9)

In [4]:
#county with the higest number of cases 
cases = covid_file.sort_values("cases", ascending = False)
cases

#highest number of cases: 271371 cases
#county with highest number of cases: Los Angelese, California

,fips,county,state,lat,long,date,cases,state_code,deaths
212,6037,Los Angeles,California,34.308284,-118.228241,2020-10-01,271371,CA,6610
377,12086,Miami-Dade,Florida,25.611236,-80.551706,2020-10-01,170882,FL,3284
633,17031,Cook,Illinois,41.841448,-87.816588,2020-10-01,146152,IL,5229
2706,48201,Harris,Texas,29.858649,-95.393395,2020-10-01,143530,TX,2607
107,4013,Maricopa,Arizona,33.348359,-112.491815,2020-10-01,142287,AZ,3405
...,...,...,...,...,...,...,...,...,...
2787,80048,Out of TX,Texas,0.000000,0.000000,2020-10-01,0,TX,0
781,80018,Out of IN,Indiana,0.000000,0.000000,2020-10-01,0,IN,0
803,90018,Unassigned,Indiana,0.000000,0.000000,2020-10-01,0,IN,227
2315,41069,Wheeler,Oregon,44.726982,-120.028143,2020-10-01,0,OR,0
2862,49001,Beaver,Utah,38.356571,-113.234223,2020-10-01,0,UT,0

In [5]:
#number of counties in each state 
covid_file['state'].value_counts()

Texas             256
Georgia           161
Virginia          135
Kentucky          122
Missouri          117
Kansas            107
Illinois          104
North Carolina    102
Iowa              101
Tennessee          97
Nebraska           95
Indiana            94
Ohio               90
Minnesota          89
Michigan           85
Mississippi        84
Oklahoma           79
Arkansas           77
Wisconsin          74
Alabama            69
Pennsylvania       69
Florida            69
South Dakota       68
Colorado           66
Louisiana          66
New York           64
California         60
Montana            58
West Virginia      57
North Dakota       55
South Carolina     48
Idaho              46
Washington         41
Oregon             38
New Mexico         35
Alaska             31
Utah               31
Maryland           26
Wyoming            25
New Jersey         23
Nevada             19
Maine              18
Arizona            17
Massachusetts      16
Vermont            16
New Hampshire      12
Connecticut        10
Rhode Island        7
Hawaii              7
Delaware            5
Name: state, dtype: int64

In [6]:
#number of deaths per state

grouped_data_deaths_state = covid_file[['state', 'deaths']].groupby('state').sum()
grouped_data_deaths_state

                deaths
state
Alabama           2548
Alaska              57
Arizona           5674
Arkansas          1384
California       15973
Colorado          2054
Connecticut       4511
Delaware           636
Florida          14444
Georgia           7063
Hawaii             139
Idaho              472
Illinois          8940
Indiana           3645
Iowa              1366
Kansas             672
Kentucky          1191
Louisiana         5519
Maine              141
Maryland          3949
Massachusetts     9479
Michigan          7024
Minnesota         2102
Mississippi       2979
Missouri          1949
Montana            181
Nebraska           493
Nevada            1603
New Hampshire      441
New Jersey       16140
New Mexico         882
New York         33159
North Carolina    3579
North Dakota       256
Ohio              4817
Oklahoma          1035
Oregon             560
Pennsylvania      8144
Rhode Island      1117
South Carolina    3400
South Dakota       236
Tennessee         2501
Texas            16130
Utah               377
Vermont             58
Virginia          3225
Washington        2132
West Virginia      359
Wisconsin         1348
Wyoming             53

In [7]:
#number of cases per state

grouped_data_cases_state = covid_file[['state', 'cases']].groupby('state').sum()
grouped_data_cases_state

                 cases
state
Alabama         155744
Alaska            7948
Arizona         219212
Arkansas         84821
California      822205
Colorado         71197
Connecticut      57742
Delaware         20787
Florida         709144
Georgia         319359
Hawaii           12515
Idaho            42561
Illinois        297884
Indiana         121176
Iowa             90428
Kansas           59514
Kentucky         69728
Louisiana       166584
Maine             5428
Maryland        125510
Massachusetts   132691
Michigan        133201
Minnesota       100200
Mississippi      98886
Missouri        115630
Montana          13500
Nebraska         46185
Nevada           80410
New Hampshire     8317
New Jersey      205889
New Mexico       29661
New York        460031
North Carolina  212898
North Dakota     22218
Ohio            155314
Oklahoma         88369
Oregon           33862
Pennsylvania    165044
Rhode Island     24914
South Carolina  148323
South Dakota     23136
Tennessee       197432
Texas           776736
Utah             60614
Vermont           1755
Virginia        148536
Washington       88116
West Virginia    16026
Wisconsin       125161
Wyoming           6083

# Working with the demography data (20 percent)


The data (`acs2017_county_data.csv`) is coming from https://www.kaggle.com/muonneutrino/us-census-demographic-data

Read the data description on the website, and answer the following.

## Read the data

- Read the data and print the first 5 rows

In [8]:
county_file = pd.read_csv(r"C:\Users\jacob\Downloads\acs2017_county_data.csv")

county_file.head(5)

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

## Explore the data

- How many rows in the data?
- Which column do you use to merge this demography data with Covid-19 data?
- Which columns to drop from the demography dataset (these are potentially duplicated in covid 19)?

In [9]:
#number of rows in dataset 
county_file.shape

#3220 rows in dataset

(3220, 37)

In [10]:
#we merge the datasets using the fips column for covid_file and the CountyID column for count_file as they have the same vales concerning individual counties  columns

In [11]:
#the duplicated columns we drop from this dataset include the columns state, and county

## Merge the data

- Merge two data frames
- Answer the following questions
  - Calculate the deaths/cases per 1000 population
  - Find the maximum of highest deaths/cases per 1000 population and their county names 
- Aggregate the data at the state level and find the following
  - Calculate the number of total cases/deaths per 1000 population
  - Which state had the highest cases/deaths, how many cases/deaths?

In [12]:
#Merging the Two Dataframes 

covid_file.rename(columns = {'fips':'CountyId'}, inplace = True) 

df_merge = pd.merge(covid_file, county_file, on = "CountyId")

df_merge.drop("State", inplace = True, axis = 1)
df_merge.drop("County", inplace = True, axis = 1)

df_merge

,CountyId,county,state,lat,long,date,cases,state_code,deaths,TotalPop,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Autauga,Alabama,32.539527,-86.644082,2020-10-01,1798,AL,28,55036,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Baldwin,Alabama,30.727750,-87.722071,2020-10-01,5997,AL,53,203360,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Barbour,Alabama,31.868263,-85.387129,2020-10-01,898,AL,7,26201,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Bibb,Alabama,32.996421,-87.125115,2020-10-01,672,AL,10,22580,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Blount,Alabama,33.982109,-86.567906,2020-10-01,1634,AL,15,57667,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,56037,Sweetwater,Wyoming,41.659439,-108.882788,2020-10-01,342,WY,2,44527,...,2.8,1.3,1.5,20.5,22739,78.4,17.8,3.8,0.0,5.2
3137,56039,Teton,Wyoming,43.935225,-110.589080,2020-10-01,591,WY,1,22923,...,11.7,3.8,5.7,14.3,14492,82.1,11.4,6.5,0.0,1.3
3138,56041,Uinta,Wyoming,41.287818,-110.547578,2020-10-01,356,WY,2,20758,...,1.1,1.3,2.0,19.9,9528,71.5,21.5,6.6,0.4,6.4
3139,56043,Washakie,Wyoming,43.904516,-107.680187,2020-10-01,116,WY,6,8253,...,6.9,1.3,4.4,14.3,3833,69.8,22.0,8.1,0.2,6.1
3140,56045,Weston,Wyoming,43.839612,-104.567488,2020-10-01,39,WY,0,7117,...,3.0,1.6,6.9,25.7,3407,68.2,21.9,8.8,1.1,2.2

In [13]:
#adding deaths per 1000 of the population per county column

df_merge["deaths per 1000"] =  df_merge["deaths"] / (df_merge["TotalPop"] / 1000)  

df_merge

,CountyId,county,state,lat,long,date,cases,state_code,deaths,TotalPop,...,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,deaths per 1000
0,1001,Autauga,Alabama,32.539527,-86.644082,2020-10-01,1798,AL,28,55036,...,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2,0.508758
1,1003,Baldwin,Alabama,30.727750,-87.722071,2020-10-01,5997,AL,53,203360,...,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5,0.260622
2,1005,Barbour,Alabama,31.868263,-85.387129,2020-10-01,898,AL,7,26201,...,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4,0.267165
3,1007,Bibb,Alabama,32.996421,-87.125115,2020-10-01,672,AL,10,22580,...,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2,0.442870
4,1009,Blount,Alabama,33.982109,-86.567906,2020-10-01,1634,AL,15,57667,...,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9,0.260114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,56037,Sweetwater,Wyoming,41.659439,-108.882788,2020-10-01,342,WY,2,44527,...,1.3,1.5,20.5,22739,78.4,17.8,3.8,0.0,5.2,0.044917
3137,56039,Teton,Wyoming,43.935225,-110.589080,2020-10-01,591,WY,1,22923,...,3.8,5.7,14.3,14492,82.1,11.4,6.5,0.0,1.3,0.043624
3138,56041,Uinta,Wyoming,41.287818,-110.547578,2020-10-01,356,WY,2,20758,...,1.3,2.0,19.9,9528,71.5,21.5,6.6,0.4,6.4,0.096348
3139,56043,Washakie,Wyoming,43.904516,-107.680187,2020-10-01,116,WY,6,8253,...,1.3,4.4,14.3,3833,69.8,22.0,8.1,0.2,6.1,0.727008
3140,56045,Weston,Wyoming,43.839612,-104.567488,2020-10-01,39,WY,0,7117,...,1.6,6.9,25.7,3407,68.2,21.9,8.8,1.1,2.2,0.000000

In [14]:
#sorting data to find the county with the highest deaths per 1000

deaths_sorted = df_merge.sort_values("deaths per 1000", ascending = False)
deaths_sorted

#Hancock county in Georgia has the highest covid deaths per 1000 at 4.961

,CountyId,county,state,lat,long,date,cases,state_code,deaths,TotalPop,...,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,deaths per 1000
455,13141,Hancock,Georgia,33.272157,-82.997669,2020-10-01,397,GA,43,8667,...,0.0,4.7,29.4,2126,66.8,26.8,6.4,0.0,4.0,4.961348
2854,51595,Emporia,Virginia,36.694556,-77.534061,2020-10-01,260,VA,26,5495,...,3.5,2.9,17.9,1893,77.8,17.6,4.5,0.0,20.4,4.731574
2866,51640,Galax,Virginia,36.666019,-80.917031,2020-10-01,419,VA,30,6788,...,0.7,2.4,18.6,2901,82.0,12.2,5.7,0.0,5.5,4.419564
505,13243,Randolph,Georgia,31.766228,-84.757324,2020-10-01,331,GA,29,7206,...,2.4,6.0,21.4,2639,75.9,18.9,5.2,0.0,8.9,4.024424
1130,22037,East Feliciana,Louisiana,30.844254,-91.049767,2020-10-01,1742,LA,72,19553,...,0.2,2.5,30.6,6920,71.2,24.6,3.9,0.4,6.1,3.682299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1714,31123,Morrill,Nebraska,41.717118,-103.006141,2020-10-01,79,NE,0,4903,...,1.1,9.1,17.8,2417,68.5,20.9,10.2,0.5,3.7,0.000000
1715,31125,Nance,Nebraska,41.397502,-97.993273,2020-10-01,51,NE,0,3569,...,0.8,5.6,19.4,1792,71.0,14.2,13.8,1.0,2.0,0.000000
1716,31127,Nemaha,Nebraska,40.385148,-95.854340,2020-10-01,132,NE,0,7041,...,0.3,4.6,19.6,3444,67.1,25.2,7.7,0.0,5.7,0.000000
1717,31129,Nuckolls,Nebraska,40.176379,-98.047440,2020-10-01,17,NE,0,4318,...,0.1,8.8,16.1,2224,69.0,13.6,17.0,0.4,1.7,0.000000
3140,56045,Weston,Wyoming,43.839612,-104.567488,2020-10-01,39,WY,0,7117,...,1.6,6.9,25.7,3407,68.2,21.9,8.8,1.1,2.2,0.000000

In [15]:
#number of cases per 1000 in each county

df_merge["cases per 1000"] =  df_merge["cases"] / (df_merge["TotalPop"] / 1000)  

df_merge

,CountyId,county,state,lat,long,date,cases,state_code,deaths,TotalPop,...,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,deaths per 1000,cases per 1000
0,1001,Autauga,Alabama,32.539527,-86.644082,2020-10-01,1798,AL,28,55036,...,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2,0.508758,32.669525
1,1003,Baldwin,Alabama,30.727750,-87.722071,2020-10-01,5997,AL,53,203360,...,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5,0.260622,29.489575
2,1005,Barbour,Alabama,31.868263,-85.387129,2020-10-01,898,AL,7,26201,...,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4,0.267165,34.273501
3,1007,Bibb,Alabama,32.996421,-87.125115,2020-10-01,672,AL,10,22580,...,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2,0.442870,29.760850
4,1009,Blount,Alabama,33.982109,-86.567906,2020-10-01,1634,AL,15,57667,...,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9,0.260114,28.335096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,56037,Sweetwater,Wyoming,41.659439,-108.882788,2020-10-01,342,WY,2,44527,...,1.5,20.5,22739,78.4,17.8,3.8,0.0,5.2,0.044917,7.680733
3137,56039,Teton,Wyoming,43.935225,-110.589080,2020-10-01,591,WY,1,22923,...,5.7,14.3,14492,82.1,11.4,6.5,0.0,1.3,0.043624,25.781966
3138,56041,Uinta,Wyoming,41.287818,-110.547578,2020-10-01,356,WY,2,20758,...,2.0,19.9,9528,71.5,21.5,6.6,0.4,6.4,0.096348,17.150014
3139,56043,Washakie,Wyoming,43.904516,-107.680187,2020-10-01,116,WY,6,8253,...,4.4,14.3,3833,69.8,22.0,8.1,0.2,6.1,0.727008,14.055495
3140,56045,Weston,Wyoming,43.839612,-104.567488,2020-10-01,39,WY,0,7117,...,6.9,25.7,3407,68.2,21.9,8.8,1.1,2.2,0.000000,5.479837

In [16]:
#sorting data to find the county with the highest cases per 1000

cases_sorted = df_merge.sort_values("cases per 1000", ascending = False)
cases_sorted

#Trousdale county in Tennessee has the highest covid case rate per 1000 at 191.041

,CountyId,county,state,lat,long,date,cases,state_code,deaths,TotalPop,...,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,deaths per 1000,cases per 1000
2511,47169,Trousdale,Tennessee,36.390262,-86.160880,2020-10-01,1676,TN,7,8773,...,4.9,29.2,3834,76.3,16.1,7.6,0.0,8.2,0.797903,191.040693
411,13053,Chattahoochee,Georgia,32.343412,-84.788092,2020-10-01,1678,GA,1,11096,...,29.2,15.5,2210,55.6,39.3,4.9,0.2,15.2,0.090123,151.225667
150,5079,Lincoln,Arkansas,33.953172,-91.740028,2020-10-01,2026,AR,15,13885,...,2.7,25.1,3359,70.4,24.0,4.6,1.0,8.1,1.080302,145.912856
351,12067,Lafayette,Florida,29.984841,-83.181666,2020-10-01,1233,FL,12,8684,...,1.3,27.2,2532,60.9,33.9,5.2,0.0,12.8,1.381852,141.985260
2474,47095,Lake,Tennessee,36.341802,-89.489219,2020-10-01,929,TN,2,7588,...,2.6,18.7,1906,59.5,31.7,7.8,1.0,11.3,0.263574,122.430153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2779,49007,Carbon,Utah,39.648348,-110.587251,2020-10-01,0,UT,0,20512,...,3.3,17.7,8906,73.7,21.5,4.3,0.4,5.4,0.000000,0.000000
2241,41069,Wheeler,Oregon,44.726982,-120.028143,2020-10-01,0,OR,0,1415,...,8.3,20.2,498,54.8,31.9,12.9,0.4,8.3,0.000000,0.000000
2778,49005,Cache,Utah,41.723306,-111.744367,2020-10-01,0,UT,0,120288,...,5.2,17.3,56905,77.5,18.0,4.4,0.2,3.6,0.000000,0.000000
2777,49003,Box Elder,Utah,41.521068,-113.083282,2020-10-01,0,UT,0,52182,...,4.0,23.5,22319,79.4,15.3,5.0,0.3,5.5,0.000000,0.000000
1751,32009,Esmeralda,Nevada,37.784367,-117.632000,2020-10-01,0,NV,0,1102,...,9.0,15.9,449,71.5,16.9,10.7,0.9,3.9,0.000000,0.000000

In [17]:
#aggregating deaths per 1000 to the state level 

grouped_data_deathsper1000_state = df_merge[['state', 'deaths per 1000']].groupby('state').mean()
max_deathsper1000 = grouped_data_deathsper1000_state.sort_values("deaths per 1000", ascending = False)
max_deathsper1000

#New Jersey has the highest deaths per 1000 at 1.589

                deaths per 1000
state
New Jersey             1.588997
Mississippi            1.260950
Louisiana              1.188034
Massachusetts          1.065112
Arizona                1.011920
Georgia                0.960006
Connecticut            0.919152
South Carolina         0.867758
Delaware               0.732730
Alabama                0.705169
Florida                0.677748
Texas                  0.636874
Rhode Island           0.621880
New York               0.553845
Arkansas               0.553609
Maryland               0.491007
Virginia               0.451377
Indiana                0.422241
North Carolina         0.403983
Tennessee              0.387619
Iowa                   0.379127
New Mexico             0.342193
Ohio                   0.337551
Pennsylvania           0.337270
Illinois               0.316483
California             0.263303
Oklahoma               0.250226
Kentucky               0.244463
Michigan               0.242711
North Dakota           0.237711
Nebraska               0.222817
South Dakota           0.218873
Idaho                  0.218604
Kansas                 0.211330
Colorado               0.202542
Washington             0.201405
Minnesota              0.192733
Missouri               0.188018
Montana                0.178334
West Virginia          0.168920
New Hampshire          0.149695
Nevada                 0.146282
Wisconsin              0.142030
Oregon                 0.131562
Wyoming                0.106333
Utah                   0.089305
Maine                  0.074759
Hawaii                 0.049279
Vermont                0.047394
Alaska                 0.036581

In [18]:
#aggregating cases per 1000 to the state level 

grouped_data_casesper1000_state = df_merge[['state', 'cases per 1000']].groupby('state').mean()
max_casesper1000 = grouped_data_casesper1000_state.sort_values("cases per 1000", ascending = False)
max_casesper1000

#Louisiana has the highest deaths per 1000 at 38.253

                cases per 1000
state
Louisiana            38.252919
Florida              38.156496
Mississippi          37.452403
Alabama              34.122184
Georgia              32.381425
Arizona              31.484648
Tennessee            31.276748
South Carolina       30.703627
Arkansas             28.030275
Iowa                 24.744009
North Dakota         23.172926
Delaware             22.560245
South Dakota         22.500799
Texas                22.419843
North Carolina       20.529821
Idaho                20.428958
New Jersey           20.336554
Oklahoma             19.553014
Wisconsin            17.146251
Virginia             16.942067
Kansas               16.643416
Missouri             16.625501
California           16.557608
Illinois             16.434561
Maryland             16.013716
Nebraska             15.174351
Minnesota            15.171714
Indiana              14.873210
Massachusetts        13.626863
Washington           12.822398
Kentucky             12.821506
Rhode Island         12.698005
Connecticut          12.522165
Montana              11.980339
New Mexico           11.189591
Ohio                 10.860235
New York             10.514201
Wyoming              10.094054
Colorado              9.862922
Oregon                9.772016
Nevada                9.350242
Pennsylvania          8.176146
Michigan              8.107797
Alaska                7.015130
West Virginia         6.736160
Utah                  6.655501
New Hampshire         3.696514
Hawaii                3.674195
Maine                 2.496573
Vermont               2.118164

## Data exploration

- Limit the data to the counties with more than 1000 people 
- Several variables are expected to be correlated with the high contraction rate of Covid-19, such as the racial composition of the county or household income. Check the correlation between these variables and cases/deaths rates. What do you find? Do you find any strong correlations?

In [19]:
#limiting counties to 1000 people 

df_mergelimit = df_merge[df_merge["TotalPop"] > 1000]
df_mergelimit

,CountyId,county,state,lat,long,date,cases,state_code,deaths,TotalPop,...,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,deaths per 1000,cases per 1000
0,1001,Autauga,Alabama,32.539527,-86.644082,2020-10-01,1798,AL,28,55036,...,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2,0.508758,32.669525
1,1003,Baldwin,Alabama,30.727750,-87.722071,2020-10-01,5997,AL,53,203360,...,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5,0.260622,29.489575
2,1005,Barbour,Alabama,31.868263,-85.387129,2020-10-01,898,AL,7,26201,...,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4,0.267165,34.273501
3,1007,Bibb,Alabama,32.996421,-87.125115,2020-10-01,672,AL,10,22580,...,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2,0.442870,29.760850
4,1009,Blount,Alabama,33.982109,-86.567906,2020-10-01,1634,AL,15,57667,...,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9,0.260114,28.335096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,56037,Sweetwater,Wyoming,41.659439,-108.882788,2020-10-01,342,WY,2,44527,...,1.5,20.5,22739,78.4,17.8,3.8,0.0,5.2,0.044917,7.680733
3137,56039,Teton,Wyoming,43.935225,-110.589080,2020-10-01,591,WY,1,22923,...,5.7,14.3,14492,82.1,11.4,6.5,0.0,1.3,0.043624,25.781966
3138,56041,Uinta,Wyoming,41.287818,-110.547578,2020-10-01,356,WY,2,20758,...,2.0,19.9,9528,71.5,21.5,6.6,0.4,6.4,0.096348,17.150014
3139,56043,Washakie,Wyoming,43.904516,-107.680187,2020-10-01,116,WY,6,8253,...,4.4,14.3,3833,69.8,22.0,8.1,0.2,6.1,0.727008,14.055495
3140,56045,Weston,Wyoming,43.839612,-104.567488,2020-10-01,39,WY,0,7117,...,6.9,25.7,3407,68.2,21.9,8.8,1.1,2.2,0.000000,5.479837

In [20]:
#finding correlation of racial composition 

df_mergelimit.describe
df_mergelimit.loc[:, ["Income", "Native", "Hispanic", "Black", "White", "Pacific", "Asian", "deaths per 1000", "cases per 1000"]].corr()

#stronger positive correlation between deaths per 1000 and cases per 1000 for black ethnic groups
#stronger negative correlation between deaths per 1000 and cases per 1000 for white ethnic groups

,Income,Native,Hispanic,Black,White,Pacific,Asian,deaths per 1000,cases per 1000
Income,1.000000,-0.074257,0.048214,-0.276369,0.117275,0.091160,0.460603,-0.158507,-0.191117
Native,-0.074257,1.000000,-0.041452,-0.101970,-0.292692,0.042536,-0.013170,-0.006946,0.022066
Hispanic,0.048214,-0.041452,1.000000,-0.113868,-0.597520,0.042679,0.142581,0.172569,0.207270
Black,-0.276369,-0.101970,-0.113868,1.000000,-0.600337,-0.048543,0.013244,0.503555,0.451500
White,0.117275,-0.292692,-0.597520,-0.600337,1.000000,-0.125873,-0.274033,-0.471699,-0.464729
Pacific,0.091160,0.042536,0.042679,-0.048543,-0.125873,1.000000,0.451638,-0.057632,-0.033623
Asian,0.460603,-0.013170,0.142581,0.013244,-0.274033,0.451638,1.000000,0.044279,-0.000108
deaths per 1000,-0.158507,-0.006946,0.172569,0.503555,-0.471699,-0.057632,0.044279,1.000000,0.565321
cases per 1000,-0.191117,0.022066,0.207270,0.451500,-0.464729,-0.033623,-0.000108,0.565321,1.000000

# Presidential voting in 2016 (15 percent)

It is well-known that there is a partisan divide in the US citizens' perceptions about the risk of Covid-19 and their response to it (e.g. https://www.pnas.org/content/117/39/24144, but there are numerous academic/journalistic articles you can find). In this section, you will check whether the votes in the 2016 US Presidential Election are correlated with the case/death figures.

The data (`pres16results.csv`) is coming from https://www.kaggle.com/stevepalley/2016uspresidentialvotebycounty

## Read the data and reshape/filter

- Read the data
- Reshape/filter the data
    - this data has a long format
    - you need to conduct data manipulation before the merging
    - you can either drop some rows (e.g. keep only Trump rows) or make it to the wide format

In [21]:
pres_file = pd.read_csv(r"C:\Users\jacob\Downloads\pres16results.csv")
pres_file.head()

,county,fips,cand,st,pct_report,votes,total_votes,pct,lead
0,NaN,US,Donald Trump,US,0.9951,60350241.0,127592176.0,0.472993,Donald Trump
1,NaN,US,Hillary Clinton,US,0.9951,60981118.0,127592176.0,0.477938,Donald Trump
2,NaN,US,Gary Johnson,US,0.9951,4164589.0,127592176.0,0.032640,Donald Trump
3,NaN,US,Jill Stein,US,0.9951,1255968.0,127592176.0,0.009844,Donald Trump
4,NaN,US,Evan McMullin,US,0.9951,451636.0,127592176.0,0.003540,Donald Trump

In [22]:
pres_file.describe

<bound method NDFrame.describe of                   county   fips             cand   st  pct_report       votes  \
0                    NaN     US     Donald Trump   US      0.9951  60350241.0
1                    NaN     US  Hillary Clinton   US      0.9951  60981118.0
2                    NaN     US     Gary Johnson   US      0.9951   4164589.0
3                    NaN     US       Jill Stein   US      0.9951   1255968.0
4                    NaN     US    Evan McMullin   US      0.9951    451636.0
...                  ...    ...              ...  ...         ...         ...
18470    Yauco Municipio  72153              NaN  NaN         NaN         NaN
18471     Midway Islands  74300              NaN  NaN         NaN         NaN
18472   St. Croix Island  78010              NaN  NaN         NaN         NaN
18473    St. John Island  78020              NaN  NaN         NaN         NaN
18474  St. Thomas Island  78030              NaN  NaN         NaN         NaN

       total_votes       pct          lead
0      127592176.0  0.472993  Donald Trump
1      127592176.0  0.477938  Donald Trump
2      127592176.0  0.032640  Donald Trump
3      127592176.0  0.009844  Donald Trump
4      127592176.0  0.003540  Donald Trump
...            ...       ...           ...
18470          NaN       NaN           NaN
18471          NaN       NaN           NaN
18472          NaN       NaN           NaN
18473          NaN       NaN           NaN
18474          NaN       NaN           NaN

[18475 rows x 9 columns]>

In [23]:
#sorting the dataframe to just show the number of votes given to Trump 

pres_file_sub = pres_file[pres_file['cand'] == "Donald Trump"] 
pres_file_sub

,county,fips,cand,st,pct_report,votes,total_votes,pct,lead
0,NaN,US,Donald Trump,US,0.9951,60350241.0,127592176.0,0.472993,Donald Trump
33,NaN,CA,Donald Trump,CA,1.0000,3184721.0,9631972.0,0.330641,Hillary Clinton
37,NaN,FL,Donald Trump,FL,1.0000,4605515.0,9386750.0,0.490640,Donald Trump
43,NaN,TX,Donald Trump,TX,0.9996,4681590.0,8903237.0,0.525830,Donald Trump
48,NaN,NY,Donald Trump,NY,0.9966,2640570.0,7046175.0,0.374752,Hillary Clinton
...,...,...,...,...,...,...,...,...,...
18327,Clark County,16033,Donald Trump,ID,1.0000,203.0,283.0,0.717314,Donald Trump
18335,Arthur County,31005,Donald Trump,NE,1.0000,237.0,263.0,0.901141,Donald Trump
18340,Kenedy County,48261,Donald Trump,TX,1.0000,84.0,186.0,0.451613,Hillary Clinton
18343,King County,48269,Donald Trump,TX,1.0000,149.0,159.0,0.937107,Donald Trump
18347,Loving County,48301,Donald Trump,TX,1.0000,57.0,64.0,0.890625,Donald Trump

In [24]:
#getting rid of NaN values in the dataframe and dropping duplicate columns 

pres_file_sub.dropna(inplace = True )

pres_file_sub.drop("county", inplace = True, axis = 1)
pres_file_sub.drop("st", inplace = True, axis = 1)

C:\Users\jacob\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\jacob\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

## Merge the data and explore the relations

- Merge the presidential election results with the main data
- Explore the relations between Trump (or Clinton) vote percentage and Covid-19 variables. What do you find?

In [25]:
#merging the presidential vote dataframe with the merged covid/county dataframe

pres_file_sub.rename(columns = {'fips':'CountyId'}, inplace = True) 

convert_dict = {'CountyId': int}

pres_file_sub = pres_file_sub.astype(convert_dict) 

df_merge_pres = pd.merge(df_merge, pres_file_sub, on = "CountyId")

df_merge_pres

C:\Users\jacob\anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,CountyId,county,state,lat,long,date,cases,state_code,deaths,TotalPop,...,FamilyWork,Unemployment,deaths per 1000,cases per 1000,cand,pct_report,votes,total_votes,pct,lead
0,1001,Autauga,Alabama,32.539527,-86.644082,2020-10-01,1798,AL,28,55036,...,0.1,5.2,0.508758,32.669525,Donald Trump,1.0,18110.0,24661.0,0.734358,Donald Trump
1,1003,Baldwin,Alabama,30.727750,-87.722071,2020-10-01,5997,AL,53,203360,...,0.1,5.5,0.260622,29.489575,Donald Trump,1.0,72780.0,94090.0,0.773515,Donald Trump
2,1005,Barbour,Alabama,31.868263,-85.387129,2020-10-01,898,AL,7,26201,...,0.3,12.4,0.267165,34.273501,Donald Trump,1.0,5431.0,10390.0,0.522714,Donald Trump
3,1007,Bibb,Alabama,32.996421,-87.125115,2020-10-01,672,AL,10,22580,...,0.3,8.2,0.442870,29.760850,Donald Trump,1.0,6733.0,8748.0,0.769662,Donald Trump
4,1009,Blount,Alabama,33.982109,-86.567906,2020-10-01,1634,AL,15,57667,...,0.1,4.9,0.260114,28.335096,Donald Trump,1.0,22808.0,25384.0,0.898519,Donald Trump
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3105,56037,Sweetwater,Wyoming,41.659439,-108.882788,2020-10-01,342,WY,2,44527,...,0.0,5.2,0.044917,7.680733,Donald Trump,1.0,12153.0,16661.0,0.729428,Donald Trump
3106,56039,Teton,Wyoming,43.935225,-110.589080,2020-10-01,591,WY,1,22923,...,0.0,1.3,0.043624,25.781966,Donald Trump,1.0,3920.0,12176.0,0.321945,Hillary Clinton
3107,56041,Uinta,Wyoming,41.287818,-110.547578,2020-10-01,356,WY,2,20758,...,0.4,6.4,0.096348,17.150014,Donald Trump,1.0,6154.0,8053.0,0.764187,Donald Trump
3108,56043,Washakie,Wyoming,43.904516,-107.680187,2020-10-01,116,WY,6,8253,...,0.2,6.1,0.727008,14.055495,Donald Trump,1.0,2911.0,3715.0,0.783580,Donald Trump
3109,56045,Weston,Wyoming,43.839612,-104.567488,2020-10-01,39,WY,0,7117,...,1.1,2.2,0.000000,5.479837,Donald Trump,1.0,2898.0,3334.0,0.869226,Donald Trump

In [26]:
#the link between Trump vote percentage in counties and Covid vaaraibles 

df_merge_pres.loc[:, ["pct", "cases per 1000", "deaths per 1000"]].corr()

#there is a weak negative correlation between cases and deaths of Covid per county and the counties that had a higher voter percentage of voters that voted for Trump

                      pct  cases per 1000  deaths per 1000
pct              1.000000       -0.133437        -0.233158
cases per 1000  -0.133437        1.000000         0.560493
deaths per 1000 -0.233158        0.560493         1.000000

# Summary (10 percent)

- Summarise your finding in (about) 300-600 words
- You can discuss the following (or you can just be creative)
    - Did you find any strong correlation between the demography/political variables with the case/death figures?
    - If you did, what do you find? Did it match with the common perception about who is more likely to contract the disease?
    - If not, why you think you didn't? Is it because of some data issues? Or something else?

Findings 

Demography Data

In terms of the demography data in relation to the covid data, the data analysis conducted has found a rather strong correlation between certain ethnic groups and the likelihood of covid infection and deaths. The strongest positive correlation was with the black ethnic group with covid case rate and death rate. This correlation is significant as the black ethnic group has a statistically significant larger risk at being infected and dying of covid than other ethnic groups that were analysed in the data. A possible explanation for this result is potentially due to socio-economic factors such as less access to quality healthcare. Another possible explanation for this trend is the black community is more likely to be deficient in vitamin d levels, a vitamin that plays a key role in determining the severity of covid cases. The ethnic group with the strongest negative correlation for covid infection and deaths is the white ethnic group. Possible explanations for this include that this particular ethnic group has access to better healthcare as they tend to be more affluent. Another explanation could be the white ethnic group is less likely to be deficient in vitamin d in comparison to ethnic groups with darker skin. Surprisingly household income only is only slightly negatively correlated with infection and death rate, this may be because age plays a large factor in covid severity, so older Americans who are potentially more on the affluent side are still at risk of Covid due to their age. 


Presidential Vote Data 

In regards to the presidential vote data there was surprisingly a weak negative correlation between counties that voted more for Trump and the cases and death rate. Though explanations for this could be that counties that voted had a higher percentage of Trump votes tend to be more rural counties that are less likely to be exposed to the virus as they are less populated. Large cities tend to vote more for the Democrats and they have a larger amount of ethnic minorities  and black populations which are inherently more at risk of more severe covid infections. Due to the population density of cities, they also facilitate the spread of the virus which may explain why counties that voted more for Trump have less cases and in terms of deaths counties that voted for Trump are likely to have a greater white population who, according to the data have lower death rates due to the virus in comparison to other ethnic groups.